// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Api.Data;

#nullable disable

namespace WebBanHang.Api.Migrations
{
    [DbContext(typeof(WebBanhangDbContext))]
    partial class WebBanhangDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebBanHang.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WebBanHang.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("WebBanHang.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "In order to survive the fiery Pyromeths, Martha Jones must spin three sensational yarns about the Tenth Doctor and his greatest adventures with old and new foes alike!",
                            ImageURL = "/Images/Comic/91oVGuZABHL._SL1500_.jpg",
                            Name = "Doctor Who: Once Upon A Time Lord",
                            Price = 16m,
                            Qty = 50
                        });
                });

            modelBuilder.Entity("WebBanHang.Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Comic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronic"
                        });
                });

            modelBuilder.Entity("WebBanHang.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "a"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "b"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
